### ISSUE TITLE
bug: Appveyor config commands are strings

### ISSUE THREAD

**Issue by d3viant0ne** [webpack-contrib/webpack-defaults#66]
The config is correct, it's implementation needs to be tweaked to contend with Appveyor minutia.

**Current output ( truncated )**
```
install:
  /* ... */
  - 'ps: Install-Product node $env:nodejs_version x64'

before_test:
  - 'cmd: npm install webpack@^%webpack_version%'

test_script:
  /* ... */
  - 'cmd: npm run appveyor:%job_part%'
```

- Notice that all the `command line & powershell` commands are wrapped as strings. The commands are correct, the `'` needs to be trimmed when written so Appveyor understands what they are. 

**Required output ( truncated )**
```
install:
  /* ... */
  - ps: Install-Product node $env:nodejs_version x64

before_test:
  - cmd: npm install webpack@^%webpack_version%

test_script:
  /* ... */
  - cmd: npm run appveyor:%job_part%
```
