### ISSUE TITLE
feat: Test webpack@canary in Travis

### ISSUE THREAD

**Issue by d3viant0ne** [webpack-contrib/webpack-defaults#67]
We are going to do a poor mans `canary` until webpack actually publishes one. 
Yes, I understand testing against `master` is less than optimal but testing `@beta` tags has it's own issues. i.e beta tag is removed, beta is older than latest and so on. Neither of which we can really do anything about without a bunch of scripting and in the end, canary is where we want to end up.

`Stage: Webpack @latest`
Execution is the same as the existing travis configuration setup to run using the Stages feature with the one notable difference that we are running against `latest` and not a static version to reduce the maintenance load.

`Stage: Webpack @canary`

Setup to `allow_failures` installed on `node_js: 8` only. Once webpack actually has a `canary` tag, the update to consume it will only involve removing the override `before_script:`

**Comment by d3viant0ne** [comment]
First pass ( getting stages working properly )

```
sudo: false
dist: trusty
language: node_js
branches:
  only:
    - master

jobs:
  fast_finish: true
  allow_failures:
    - env: WEBPACK_VERSION=beta
  include:
    - &test-latest
      stage: Webpack@latest
      nodejs: 6
      script: npm run travis:$JOB_PART
      env: WEBPACK_VERSION=latest JOB_PART=test
    - <<: *test-latest
      nodejs: 4.3
      env: WEBPACK_VERSION=latest JOB_PART=test
      script: npm run travis:$JOB_PART
    - <<: *test-latest
      node_js: 8
      env: WEBPACK_VERSION=latest JOB_PART=lint
      script: npm run travis:$JOB_PART
    - <<: *test-latest
      node_js: 8
      env: WEBPACK_VERSION=latest JOB_PART=coverage
      script: npm run travis:$JOB_PART
      after_success: 'bash <(curl -s https://codecov.io/bash)'
    - stage: Webpack@beta
      script: npm run travis:$JOB_PART
      node_js: 8
      env: WEBPACK_VERSION=beta JOB_PART=test

before_install:
  - 'if [[ `npm -v` != 5* ]]; then npm i -g npm@^5.0.0; fi'
  - nvm --version
  - node --version
  - npm --version
before_script:
  - |-
    if [ "$WEBPACK_VERSION" ]; then
      npm i --no-save webpack@$WEBPACK_VERSION
    fi

```
